version: '3.4'
services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=portfoliodb
    ports:
      - "5001:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./dbscripts:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hector.maganahdez@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5002:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
  api:
    image: hectoritobonito/portfolio-api:latest
    environment:
        DbConnectionString: "Server=postgresql_database; Port=5432; Database=portfoliodb; User Id=postgres; Password=admin"
    ports:
      - "5003:80"
  wireguard-admin:
    build: 
      context: ./Wireguard-admin
      dockerfile: dockerfile
    restart: always
    ports:
      - "5004:3000"
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=hectormagana.art
      - STAGING=false
    volumes:
      - /swag:/config
      - ./Nginx/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    depends_on:
      - postgresql_database
      - pgadmin
      - api
    restart: unless-stopped
volumes:
  database-data:
  pgadmin:
