name: Dump Pipeline
on:
  [push]
jobs:
  Dump-Database:
    runs-on: linode-vm
    steps:
      - name: Delete old dumps.
        working-directory: /root/source/dumps/
        run: |
         f5days=$(date +%s --date="-5 days"); for file in *.sql; do fdate=$(echo $file | tr _ -);fsec=$(date +%s --date=${fdate/.sql/});if [[ $fsec -lt $f5days ]]; then rm $file;fi;done
      - name: Dump database.
        working-directory: /root/source/dumps/
        run: |
         echo "🤓: dumping database"
         docker exec portfolio-vm_postgresql_database_1 -c -U postges > `date +%Y-%m-%d`.sql
  Transfer-Dump:
    need: Dump-Database
    runs-on: snow-backup
    steps:
      - name: Transfer dump.
        working-directory: /home/hector/source/dumps/
        run: |
          echo "🤓: transfering dump over SCP"
          rm *
          wg-quick up wg-hector
          sshpass -p '${{secrets.LINODE_PASSWORD}}' scp root@10.200.50.1:~/source/dumps/* .
          wg-quick down wg-hector