name: Portfolio Pipeline
on: [push]
jobs:
 Initial:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Redeploy Portfolio API
        working-directory: /root/source/Portfolio-vm/Portfolio-Api/
        run: |
         export DbConnectionString='${{secrets.DB_CONNECTION_STRING}}'
         echo "🤓: Refreshing API service"
         systemctl stop Portfolio-Api.service
         sudo cp Portfolio-Api.service /etc/systemd/system/Portfolio-Api.service
         systemctl daemon-reload
         systemctl start Portfolio-Api.service
      - name: Redeploy Docker Compose
        working-directory: /root/source/Portfolio-vm/
        run: |
         echo "🤓: Redeploying Docker-compose"
         docker-compose down
         docker-compose build
         docker-compose up -d
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
